### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-ERI#382]
- [ ] Bump version
- [ ] Update sample outputs
- [ ] Create release zip files
- [ ] Create release w/ release notes
- [ ] Make release documentation public
